on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'gfishfont@dfish.xyz'
          password: 'Aa1234565.'

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Dockerfile 的路径
          push: true
          tags: |
            gfishfont/gfish-ui:latest
            gfishfont/gfish-ui:${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && replace(github.ref, 'refs/tags/', '') }}
